# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='todo',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='todo',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
